repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.4.0'
    hooks:
      - id: end-of-file-fixer
        exclude: 'setup.cfg'
      - id: trailing-whitespace
        exclude: 'setup.cfg'
      - id: debug-statements
  - repo: https://github.com/asottile/pyupgrade
    rev: 'v3.2.2'
    hooks:
      - id: pyupgrade
        args:
          - --py38-plus
  - repo: https://github.com/PyCQA/isort
    rev: '5.10.1'
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: '22.10.0'
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/flake8
    rev: '6.0.0'
    hooks:
      - id: flake8
